services:
  backend-golang:
    build:
      context: ./backend-golang
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend-golang:/app
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      - GO_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=sample_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    command: >
      sh -c "if [ \"$$GO_ENV\" = \"development\" ]; then
        go run cmd/serve/main.go;
      else
        /app/backend-golang;
      fi"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app-network
  frontend-react:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-react:/app
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend-nodejs
    networks:
      - app-network