app:
  name: sample-stack-golang
  port: 8080
  version: 1.0.0
  env: development
  workers: 3 # Default worker count

server:
  port: 8080
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 120
  jwt_secret: your-secret-key

db:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  name: sample_db

redis:
  host: redis
  port: 6379

rabbitmq:
  host: rabbitmq
  port: 5672
  user: guest
  password: guest

logging:
  level: debug
  format: json
  output: stdout
  file_path: logs/app.log
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true 