app:
  name: sample-stack-golang
  version: 1.0.0
  env: development

server:
  port: 8080
  read_timeout: 15
  write_timeout: 15
  idle_timeout: 60
  jwt_secret: your-secret-key

database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  dbname: sample_stack
  sslmode: disable

logger:
  level: info
  file_path: logs/app.log
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true
  console_output: true

redis:
  host: redis
  port: 6379
  password: ""
  db: 0

rabbitmq:
  host: rabbitmq
  port: 5672
  user: guest
  password: guest
  vhost: / 