FROM golang:1.21-alpine AS development

WORKDIR /app

# Install necessary dependencies
RUN apk add --no-cache git build-base postgresql-client

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source code
COPY . .

# Expose port
EXPOSE 8080

# Set the command to run when the container starts
CMD ["go", "run", "cmd/serve/main.go"] 